#!/usr/bin/env bash
if [ -z "${PUID}" ] || [ -z "${PGID}" ]; then
	equibitd -datadir=/data
else
	create-node-user "${PUID}" "${PGID}" equibit equibit
	sudo -u equibit -p equibit equibitd -datadir=/data
fi
